language: ruby

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq emacs23
  - sudo apt-get build-dep -qq emacs24

  - test -d $HOME/.evm || git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm

  - evm install $EVM_EMACS
  - evm use $EVM_EMACS

env:
  - EVM_EMACS=emacs-23.4-bin
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin
  - EVM_EMACS=emacs-24.4-bin
  - EVM_EMACS=emacs-24.5-bin
  #- EVM_EMACS=emacs-git-snapshot

matrix:
  allow_failures:
    - env:
        - EVM_EMACS=emacs-git-snapshot

script:
  lsb_release -a && ./test-startup.sh

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
